name: "Default deployment"
stages:     
   network:
     - dns:
         path: /etc/resolv.conf
         nameservers:
         - 8.8.8.8
     - if: '[ ! -f "/run/cos/recovery_mode" ]'
       name: "Setup k3s"
       commands:
       # to avoid specifying hostnames for each boxes
       - sed -i -e 's|agent \\|agent --with-node-id|g' /etc/systemd/system/k3s-agent.service
       environment_file: "/etc/systemd/system/k3s-agent.service.env"
       # This is k3s agent node configuration
       environment:
         K3S_URL: 
         K3S_TOKEN: 
       systemctl:
         start: 
         - k3s-agent
     - commands:
       - |
            chmod 600 /etc/systemd/system/k3s-agent.service.env
       - ulimit -u unlimited
       - ulimit -n 900000
     - name: "Setup users"
      #  users:
      #   root:
      #     password: "c3os"
       authorized_keys:
        c3os: 
        - github:mudler
     - if: '[ ! -f "/usr/local/.deployed" ]'
       name: "Deploy cos-system"
       # here we specify the image to upgrade to
       commands:
         - |
             # Use `cos-deploy --docker-image <img-ref>` to deploy a custom image
             # By default latest cOS gets deployed
             cos-deploy --docker-image --force --no-verify quay.io/mudler/c3os:v1.21.4-1 && touch /usr/local/.deployed && shutdown -r now
   initramfs:
     - commands:
       - passwd -l c3os
   # Disable password, enable only ssh access
     - if: '[ ! -d "/home/c3os" ]'
       name: "Ensure home directory is present"
       commands:
       - mkdir /home/c3os
       - chmod 755 /home/c3os
       - chown -R c3os /home/c3os

