apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  chart: https://charts.jetstack.io/charts/cert-manager-v1.5.3.tgz

  set:
    installCRDs: "true"