apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: cattle-system
spec:
  chart: https://releases.rancher.com/server-charts/latest/rancher-2.6.0.tgz
  set:
    hostname: "10.86.4.95.nip.io"
    bootstrapPassword: "admin"
