---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: 1-21
  namespace: cattle-system
  labels:
    k3s-upgrade: server
spec:
  concurrency: 1
  #version:  latest
  version: "v1.21.4-1"
  nodeSelector:
    matchExpressions:
      - {key: kubernetes.io/hostname, operator: Exists}
  serviceAccountName:	system-upgrade-controller
  cordon: true
  drain:
    force: true
    disableEviction: true
  upgrade:
    image: quay.io/mudler/c3os
    command:
    - "/usr/sbin/suc-upgrade"
